sudo: false
language: java
jdk:
- oraclejdk8
cache:
  directories:
    - ~/.m2/repository
before_install:
  - mkdir -p ~/.m2
install: 
  - mvn clean package -DskipTests
deploy:
  provider: releases
  api_key:
    secure: JmCeY+yFrThEwuqiBNFc52LEeDr/J4PltMUd79V3IziilJ1tvVcodh7v3i2T2OT3odrEzCezujk5X6h8QbRNicydi3WqpkUy9UNUBgwatOSxbQFBKdjFwgxEpt1sUEnH/LVLP5ZK44rxalXzTPaEOragc6usbmw/jJDxqT0CtbT5EBwQY4evepLHZXZdvXTVM8c1Cl3xsVyQjZKU80qEvW1+6QXYIgVmxtMsLQkCe4igzBy8PvzfT2pLawfxjXf8/Nmtep7Wlf7f95z9JDiNAoUQmvZUvcgX97a8ZkTK2UHsNmtpmAPrkyF57uX8HHgsNB9yqKgqZoFpGaD/qvFjAUC1asCZqN4rdC1XqqQSIjZezbgree6WRarnqwPOqxB85jil8PNV37VoVN+VvvrOmCm2KU0YWeD2DfLs5228OyOo1bq5JsziaVO4eqvluEqaCGGkrlBjfRMXgS/R6U6qyCyjy7N+4UNndxWuHGjqqXeDq2NrdNbnz+GsdJy6s8ZJYzmWvR/oqFMKoYEae01VROcPBDcozECA/IrLf57+ONvdKCGIg8YFY7ZcA4rG9Q7LZJ4F2UI8QGlGxNfts10RHbYlMshQYyejsKGn1ILTIQld558DwZ3AJyyfbKHjZxD9N7xMDZ1v+BC5oDbso4oYtoSa9KDN4RPXObW4e3GgrNo=
  file_glob: true
  file: target/layers-service*.war
  skip_cleanup: true
  overwrite: true
  on:
    repo: bioatlas/layers-service
    all-branches: true
